# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: apt-get void
name: apt-get void
email: joao.neto.guimaraes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  me deixem falar besteira
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://netoguimaraes.github.io/" # the base hostname & protocol for your site
github_username:  netoguimaraes

footer-links:
  facebook: fb.com/joaokrustin
  github: netoguimaraes
  instagram: netuguimaraes
  
# Build settings
markdown: redcarpet
highlighter: pygments
