#Profile
name: Neto Guimarães
description: Um blog sobre tecnologia e todas as angústias e alegrias que a cercam.
footer-links:
  email: joao.neto.guimaraes@gmail.com
  instagram: netuguimarães
  facebook: fb.com/joaokrustin

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

# Handling Reading
safe:         true
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "<!--bora-->"
incremental: false

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"
